### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by fnkr** [AdamCoulterOz/terraform-provider-azurehelpers#1]
Hi. I would like to use your code but cannot do so because it's not (yet) open source licensed. Would you mind adding a LICENSE file (e.g. MIT license) to the repo?

**Comment by AdamCoulterOz** [comment]
It's published on the registry already... but I've also added MIT license.

https://registry.terraform.io/providers/AdamCoulterOz/azurehelpers/latest

**Comment by fnkr** [comment]
Thank you very much!

**Comment by AdamCoulterOz** [comment]
@fnkr - FYI - I just published v0.2.0 which now has documentation included..

https://registry.terraform.io/providers/AdamCoulterOz/azurehelpers/latest/docs
